project:
  type: website
  output-dir: docs


website:
  title: "TECH3 Applied statistics"
  image: images/nhh.png
  page-navigation: true
  navbar:
    background: primary
    logo: images/nhh.png
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Calender"
        href: calender.qmd
      - text: "Modules"
        href: 1-intro.qmd
      - text: "Old exams"
        href: oldexams.qmd


  sidebar:
    # - title: "Cases"
    #   style: "docked"
    #   collapse-level: 1
    #   search: true
    #   background: light
    #   contents:
    #     - case-1.qmd
    #     - case-2.qmd
        
    - title: "Modules"
      contents: 
         - section: "Module 1: Summarizing and visualizing data"
           contents:
             - href: 1-intro.qmd
               text: "Introduction"
             - href: 1-textbook.qmd
               text: "Textbook"
             - 1-statistical-thinking.qmd
             - 1-working-with-data.qmd
             - 1-summarizing-data.qmd
             - 1-summary-statistics.qmd
             - 1-data-visualization.qmd
             - 1-plotting-tools.qmd
             - 1-idealised_representations.qmd
             - 1-gapminder.qmd
             - 1-exercises.qmd
         - section: "Module 2: Probability, random variables, probability distributions and simulations."
           contents: 
             - href: 2-intro.qmd
               text: "Introduction"
             - href: 2-textbook.qmd
               text: "Textbook"
             - 2-what-is-probability.qmd
             - 2-basic-concepts-in-probability.qmd
             - 2-basic-probability-rules.qmd
             - 2-conditional-probability.qmd
             - 2-independent-events.qmd
             - 2-bayes-rule.qmd
             - 2-discrete-random-variables-and-distributions.qmd
             - 2-exp-var-discrete.qmd
             - 2-distribution-functions-in-python.qmd
             - 2-exercises.qmd
         - section: "Module 3: Estimation, sampling distributions and resampling"
           contents: 
             - href: 3-intro.qmd
               text: "Introduction"
             - href: 3-textbook.qmd
               text: "Textbook"
             - 3-population-vs-sample.qmd
             - 3-what-is-a-model.qmd
             - 3-sampling-error.qmd
             - 3-central-limit-theorem.qmd
             - 3-what-is-an-estimator.qmd
             - 3-maximum-likelihood.qmd
             - 3-random-number-generation.qmd
             - 3-monte-carlo-simulation.qmd
             - 3-bootstrap.qmd
             - 3-exercises.qmd
             # - 3-python.qmd
         - section: "Module 4: Designing studies, hypothesis testing, and quantifying effects"
           contents: 
             - href: 4-intro.qmd
               text: "Introduction"
             - href: 4-textbook.qmd
               text: "Textbook"
             - 4-hypothesis-testing.qmd
             - 4-hypothesis-testing-in-python.qmd
             - 4-power-analysis.qmd
             - 4-videos.qmd
             - 4-exercises.qmd
         - section: "Module 5: Measuring relationships and fitting models"
           contents: 
             - href: 5-intro.qmd
               text: "Introduction"
             - href: 5-textbook.qmd
               text: "Textbook"
             - 5-categorical-relationships.qmd
             - 5-contingency-tables.qmd
             - 5-simpsons-paradox.qmd
             - 5-continuous-relationships-correlation.qmd
             - 5-correlation-and-causation.qmd
             - 5-linear-regression.qmd
             - 5-assessing-the-model.qmd
             - 5-prediction-models.qmd
             - 5-logistic-regression.qmd
             - 5-exercises.qmd
            
    # - title: "Python basics"
    #   contents:
    #     - pythonbasics.qmd
        # navigation items
  
    - title: "Old exams"
      contents:
        - oldexams.qmd
        # navigation items

        

editor: visual


          
format:
  html:
    theme: 
        - cosmo
        - custom.scss
    css: style.css
    toc: true
    # toc-depth: 1
    # fontsize: 1.1em
    # linestretch: 1.7
    # number-sections: true
    # number-debth: 2
    # html-math-method: katex
